### ISSUE TITLE
Issue with TRACE_DSP names in Release?

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_perfetto#11]
Not 100% sure but I think I'm seeing some names collapse in release mode (perhaps due to inlining?)

![Google Chrome - 2023-01-25 10@2x](https://user-images.githubusercontent.com/472/214844813-0a56a071-80cd-47cb-bec3-903ed2f95af4.jpg)

**Comment by benthevining** [comment]
I'm not sure I see the problem in the above screenshot? Is it the "assemble" slice at the bottom with no qualifying scope?

**Comment by sudara** [comment]
Wasn't sure if related to #13, but the issue is that SineMachineVoice::renderNextBlock is being used for methods encapsulated by it that should have their own annotation. For example one of them is a function actually called ::renderIfNeeded

**Comment by benthevining** [comment]
Interesting. It's possible it's due to inlining, I'm not really sure how to verify that though.

**Comment by sudara** [comment]
Can't really find much out there about `__PRETTY_FUNCTION__` being useless due to release mode optimizations. Curious....

**Comment by benthevining** [comment]
As far as I know, the only way to definitely check if something got inlined is to inspect the actual generated assembly... 😬
