### ISSUE TITLE
Improve Perfetto output of TRACE_DSP/COMPONENT

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_perfetto#2]
TRACE_DSP and TRACE_COMPONENT are helpers that make it easy just to drop one at the start of a function and get things reporting without having to pass redundant categories and function names.

They currently use `PERFETTO_DEBUG_FUNCTION_IDENTIFIER` under the hood, which basically calls `__PRETTY_FUNCTION__`

However, it's not so pretty, this is an example in the UI:

<img width="812" alt="Google Chrome - 2022-12-16 25@2x" src="https://user-images.githubusercontent.com/472/208166554-6bed7f2c-5b6f-4663-9d03-c164cb46d5c8.png">

Yeahh.. so the strings look like this:

```
auto AudioProcessor::processBlock(juce::AudioBuffer<float> &, juce::MidiBuffer &)::(anonymous class)::operator()()::(anonymous class)::operator()(uint32_t) const
```

What we'd like to see is no return value or arguments, etc:

```
 AudioProcessor::processBlock
```

I tried implementing something constexpr/eval along these lines:

```
consteval std::string_view class_and_method_name (const char* s)
{
    std::string_view prettyFunction (s);
    size_t start = prettyFunction.find (' ') + 1;
    size_t end = prettyFunction.find ('(');
    return prettyFunction.substr (start, 20);
}

    // std::string cannot be used in consteval context
    // but string view isn't null terminated
    // so no way to pass the const char * properly to perfetto without going through std::string
    // otherwise the string isn't properly terminated
    #define TRACE_DSP(...) TRACE_EVENT ("dsp", perfetto::StaticString(class_and_method_name (PERFETTO_DEBUG_FUNCTION_IDENTIFIER()).data()), ##__VA_ARGS__)
    #define TRACE_COMPONENT(...) TRACE_EVENT ("component", perfetto::StaticString(class_and_method_name (PERFETTO_DEBUG_FUNCTION_IDENTIFIER()).data()), ##__VA_ARGS__)
```

See: https://stackoverflow.com/a/64384924

However, it looks like either a std::string is needed (which means constexpr is out the window) OR  view.data isn't null terminated, which means it doesn't truncate (it does start after the first space, which means we at least drop the return type from the string)

![Google Chrome - 2022-11-29 47@2x](https://user-images.githubusercontent.com/472/204663719-5515ca23-049e-4835-b222-88742218e676.jpg)

Goals:

* [ ] works with C++17 or 20, ideally uses consteval when C++20
* [ ] Either 100% compile time or very cheap/fast string manip of the string
* [ ] Add clarification in documentation that trace events are not per-function, but per-scope — so you can have multiple in a function, put one in a for-loop, etc

**Comment by sudara** [comment]
@benthevining I'm trying to release today, so taking one more look here to see if there's a pragmatic solution....

**Comment by sudara** [comment]
Ended up doing it with compile time arrays. I'm sure there's a more elegant solution, but you can check it out here: https://github.com/sudara/melatonin_perfetto/blob/301d0ff52bff9b5fdbe2399da01a965bb76cfd28/melatonin_perfetto/melatonin_perfetto.h#L105

**Comment by benthevining** [comment]
Nice solution! I was hitting some road blocks here, so I'm glad you were able to get it working!
