### ISSUE TITLE
CMake Option for setting allocated buffer size

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_perfetto#3]
Not 100% if this should be CMake or just API

However, we set the buffer size to 8MB right now. I *believe* that allocates on boot and then is used to populate with events. If you boot the app and events overflow the 8MB, from what I can tell, the trace just doesn't work over on https://perfetto.dev ?

I have mine set to 80MB right now, but a larger allocation like that results in longer boot times.

* [ ] Pick a better medium size, perhaps 32MB? 8MB seems too small
* [ ] Add CMake option (what do you think, makes sense? Or better just to optionally pass a number to `beginSession`? )
* [ ] Make sure docs are in line

**Comment by benthevining** [comment]
I would probably recommend putting this option in the C++ API. It would be possible to allow the user to override the default value by setting a CMake variable, but it seems to me that if someone is willing to change their CMake code to customize this, they wouldn't mind changing their C++ code.

**Comment by sudara** [comment]
Closed by 9557fc6760a4dcc7e53058685cf29bebc9dfb073
