### ISSUE TITLE
Add cross-platform GitHub Actions tests

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_perfetto#7]
Followup to #4 

- [x] Create a GitHub action for QC
- [x] Add test case(s) to verify that the correct dump files are indeed created

cc @benthevining

**Comment by benthevining** [comment]
Interestingly, there are a couple of test failures on Linux. Is that a platform you'd like to put time & energy into supporting? I don't have a Linux machine available so we may have to rely on repeated GH Actions builds to debug this 😬

**Comment by sudara** [comment]
No need for linux. Assuming the tests are only running in the context of this project, it's fair to stick with macOS and Windows. Down the line if there's someone wanting Linux support, they can help us figure it out....

**Comment by benthevining** [comment]
OK great. I'll remove Linux from the CI matrix; Mac and Windows are passing.
